www.kouarge.org/Areas/Admin/Controllers/RedirectController.cs
using KouArge.Core.DTOs;
using Microsoft.AspNetCore.Mvc;
using www.kouarge.org.ApiServices;

namespace www.kouarge.org.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RedirectController : Controller
    {
        private RedirectApiService _redirectApiService;

        public RedirectController(RedirectApiService redirectService)
        {
            _redirectApiService = redirectService;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _redirectApiService.GetAllAsync();
            return View(data.Data);
        }

        public async Task<IActionResult> Save()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Save(RedirectDto redirectDto)
        {
            if (ModelState.IsValid)
            {
                //TODO: Id kontrolü yap
                var data = await _redirectApiService.AddAsync(redirectDto);
                if (data.ErrorStatus == 1)
                {
                    ModelState.AddModelError("Name", $"Name({redirectDto.Name}) zaten mevcut.");
                    return View(redirectDto);

                }
                return RedirectToAction(nameof(Index));
            }

            return View(redirectDto);
        }

        public async Task<IActionResult> Update(int id)
        {
            var data = await _redirectApiService.GetByIdAsync(id);

            //TODO:ToastJs veya AlertifyJs ekle
            if (data == null)
                return View("Error");

            return View(data.Data);
        }

        [HttpPost]
        public async Task<IActionResult> Update(RedirectDto redirectDto)
        {
            if (ModelState.IsValid)
            {
                var success = await _redirectApiService.UpdateAsync(redirectDto);

                //TODO: Id kontrolü yap
                if (success)
                    return RedirectToAction(nameof(Index));
                else
                    return View("Error");
            }

            var redirect = await _redirectApiService.GetByIdAsync(redirectDto.Id);
            return View(redirect.Data);

        }

        public async Task<IActionResult> Delete(int id)
        {
            var success = await _redirectApiService.DeleteAsync(id);
            if (success)
                return RedirectToAction(nameof(Index));
            else
                return View("Error");
        }

    }
}

www.kouarge.org/Controllers/RedirectController.cs
using KouArge.Core.Services.ApiService;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Mvc;

namespace www.kouarge.org.Controllers
{
    public class RedirectController : Controller
    {

        private readonly IRedirectApiService _redirectService;
        public RedirectController(IRedirectApiService service)
        {
            _redirectService = service;
        }

        //[Route("R/[Action]")]
        //public async Task<IActionResult> QR1()
        //{
        //    await _redirectService.AddAsync("1");
        //    return Redirect("https://www.twitch.tv/directory/all");
        //    //ViewBag.Url = "https://www.twitch.tv/directory/all";
        //    //return View("QR");
        //}

        [Route("R/{text}")]
        public async Task<IActionResult> CustomRedirect(string text)
        {
            var remoteIpAddress = HttpContext.Features.Get<IHttpConnectionFeature>()?.RemoteIpAddress;

            var url = await _redirectService.AddCountAsync(text);

            //TODO: pasive duruma sayfa yap. yonlendir.
            if (url == null)
                return RedirectToAction("Error", "Department");

            return Redirect(url.Data);

        }

        [Route("[Action]")]
        public async Task<IActionResult> TeknikTakimBrosur(string text)
        {
            var remoteIpAddress = HttpContext.Features.Get<IHttpConnectionFeature>()?.RemoteIpAddress;
            text = "tekniktakimbrosur";
            var url = await _redirectService.AddCountAsync(text);

            //TODO: pasive duruma sayfa yap. yonlendir.
            if (url == null)
                return RedirectToAction("Error", "Department");

            return Redirect(url.Data);

        }
    }
}

www.kouarge.org/Areas/Admin/Views/Redirect/Index.cshtml
@model List<Redirect>
@{
	ViewData["Title"] = "Index";
}
<h1>Index</h1>
<a class="btn btn-primary" asp-controller="Redirect"  asp-action="Save" >New</a>
<table class="table table-stripped">
	<thead>
		<tr>
			<td>Id</td>
			<td>Name</td>
			<td>Url</td>
			<td>Count</td>
			<td>Created At</td>
			<td>Updated At</td>
			<td>Status</td>
			<td>Update</td>
			<td>Delete</td>
		</tr>
	</thead>
	<tbody>

		@foreach (var item in Model)
		{
			<tr>
				<td>@item.Id</td>
				<td>@item.Name</td>
				<td><a target="_blank" href="@item.Url">@item.Url</a></td>
				<td>@item.Count</td>
				<td>@item.CreatedAt</td>
				<td>@item.UpdatedAt</td>
				<td>
					@if (item.IsActive)
					{
						<label>Active</label>
					}
					else
					{
						<label>Pasive</label>
					}
				</td>
				<td><a class="btn btn-warning" asp-action="update" asp-controller="redirect" asp-route-id="@item.Id">Update</a></td>
				<td><a class="btn btn-danger" asp-action="delete" asp-controller="redirect" asp-route-id="@item.Id">Delete</a></td>
		
			</tr>
		}

	</tbody>
</table>

www.kouarge.org/Areas/Admin/Views/Redirect/Save.cshtml
@{
    ViewData["Title"] = "Save";
}
<h1>Save</h1>
@model RedirectDto
<div class="row">

    <div class="col-md-6">
        <form asp-action="Save" asp-controller="Redirect" method="post">

            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="Url"></label>
                <input asp-for="Url" class="form-control" />
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>

            <input type="submit" value="Save" class="btn btn-primary" />

        </form>
    </div>

</div>

www.kouarge.org/Areas/Admin/Views/Redirect/Update.cshtml
@{
    ViewData["Title"] = "Update";
}
<h1>Update</h1>
@model RedirectDto
<div class="row">

    <div class="col-md-6">
        <form asp-action="Update" asp-controller="Redirect" method="post">
            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Url"></label>
                <input asp-for="Url" class="form-control" />
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Count"></label>
                <input asp-for="Count" class="form-control" />
                <span asp-validation-for="Count" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="IsActive"></label>
                <input asp-for="IsActive" class="form-control" />
                <span asp-validation-for="IsActive" class="text-danger"></span>
            </div>

            <input type="submit" value="Update" class="btn btn-primary" />
        </form>
    </div>

</div>