www.kouarge.org/Controllers/FacultyController.cs
using KouArge.Core.DTOs;
using KouArge.Core.Services.ApiService;
using Microsoft.AspNetCore.Mvc;

namespace www.kouarge.org.Controllers
{

    public class FacultyController : Controller
    {
        private readonly IFacultyApiService _facultyApiService;

        public FacultyController(IFacultyApiService faultyApiService)
        {
            _facultyApiService = faultyApiService;
        }

        public async Task<IActionResult> Index()
        {
            var faculty = await _facultyApiService.GetAllAsync();
            return View(faculty);
            //return RedirectToAction("maintenance", "Home");
        }

        public async Task<IActionResult> Save()
        {
            return View();
            //return RedirectToAction("maintenance", "Home");

        }

        [HttpPost]
        public async Task<IActionResult> Save(FacultyDto facultyDto)
        {
            if (ModelState.IsValid)
            {
                await _facultyApiService.Save(facultyDto);
                return RedirectToAction(nameof(Index));
            }

            return View(facultyDto);
        }

        //[ServiceFilter(typeof(NotFoundFilter<Department>))]
        public async Task<IActionResult> Update(int id)
        {
            var faculty = await _facultyApiService.GetByIdAsync(id);

            if (faculty == null)
                return View("Error");

            return View(faculty);
            //return RedirectToAction("maintenance", "Home");


        }

        [HttpPost]
        public async Task<IActionResult> Update(FacultyDto facultyDto)
        {

            if (ModelState.IsValid)
            {
                var success = await _facultyApiService.UpdateAsync(facultyDto);

                if (success)
                    return RedirectToAction(nameof(Index));

                //hata sayfasına yonlendir
            }

            return View(facultyDto);

        }

        public async Task<IActionResult> Delete(int id)
        {
            var success = await _facultyApiService.DeleteAsync(id);

            if (success)
                return RedirectToAction(nameof(Index));
            else
                //hata sayafası
                return RedirectToAction(nameof(Index));

        }


    }
}

www.kouarge.org/Views/Faculty/Index.cshtml
@model List<FacultyDto>
@{
	ViewData["Title"] = "Index";
}
<h1>Index</h1>
<a class="btn btn-primary" asp-action="save" asp-controller="faculty">New</a>
<table class="table table-stripped">
	<thead>
		<tr>
			<td>Id</td>
			<td>Name</td>
			<td>Campus</td>
			<td>Created At</td>
			<td>Update</td>
		</tr>
	</thead>
	<tbody>

		@foreach (var item in Model)
		{
			<tr>
				<td>@item.Id</td>
				<td>@item.Name</td>
				<td>@item.Campus</td>
				<td>@item.CreatedAt</td>
				<td>
				<a class="btn btn-warning" asp-action="update" asp-controller="faculty" asp-route-id="@item.Id">Update</a>	
				</td>
				<td> 
				<a class="btn btn-danger" asp-action="delete" asp-controller="faculty" asp-route-id="@item.Id">Delete</a>	
				</td>
			</tr>
		}

	</tbody>
</table>

www.kouarge.org/Views/Faculty/Save.cshtml
@{
    ViewData["Title"] = "Save";
}
<h1>Save</h1>
@model FacultyDto
<div class="row">

    <div class="col-md-6">
        <form asp-action="Save" asp-controller="faculty" method="post">

            <div class="form-group">
                <label asp-for="Name" ></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" ></span>
            </div>

            
            <div class="form-group">
                <label asp-for="Campus" ></label>
                <input asp-for="Campus" class="form-control" />
                <span asp-validation-for="Campus" class="text-danger" ></span>
            </div>



            <input type="submit" value="Save" class="btn btn-primary" />

        </form>
    </div>
    
</div>

www.kouarge.org/Views/Faculty/Update.cshtml
@{
    ViewData["Title"] = "Update";
}
<h1>Update</h1>
@model FacultyDto
<div class="row">

    <div class="col-md-6">
        <form asp-action="Update" asp-controller="Faculty" method="post">
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" ></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" ></span>
            </div>

              <div class="form-group">
                <label asp-for="Campus" ></label>
                <input asp-for="Campus" class="form-control" />
                <span asp-validation-for="Campus" class="text-danger" ></span>
            </div>

            <input type="submit" value="Update" class="btn btn-primary" />

        </form>
    </div>
    
</div>